### ISSUE TITLE
Feature: I-Frames Mode

### ISSUE THREAD

**Issue by rx-dev** [ErrorCraft/Score-Based-Damage#1]
It would be nice if you could toggle whether or not the custom damage applies I-Frames! I might PR this later ;)

**Comment by ErrorCraft** [comment]
What would be a good way to apply the option/toggle, maybe a storage, or just two different functions?

**Comment by rx-dev** [comment]
I think alt function would be fine?

**Comment by ErrorCraft** [comment]
Would it still have to play the "hurt" sound when applying the damage, because I think it looks kind of weird to not see the visual effects (the red flash and screen tilt) but still hear the sound?

**Comment by ErrorCraft** [comment]
Currently added it without the sound.
